version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    assignees:
      - Sharparam
    labels:
      - dependencies
      - 'dependencies:cargo'
    reviewers:
      - Sharparam
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - Sharparam
    labels:
      - dependencies
      - 'dependencies:github-actions'
    reviewers:
      - Sharparam
