[package]
name = "facti"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Factorio mod tool"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive", "env"] }
clap_complete = "4.3.2"
directories = "5.0.1"
facti-api = { version = "0.1.0", features = ["blocking"], path = "../api" }
facti-lib = { version = "0.1.0", path = "../lib" }
git2 = { version = "0.17.2", default-features = false }
indoc = "2.0.3"
rpassword = "7.2.0"
serde = "1.0.183"
serde_json = "1.0.104"
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", features = ["serde"] }
