[package]
name = "facti"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Factorio mod tool"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["command-line-utilities", "development-tools"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
ron = ["dep:ron"]
sexpr = ["dep:serde-lexpr"]
yaml = ["dep:serde_yaml"]

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive", "env"] }
clap_complete = "4.3.2"
directories = "5.0.1"
facti-api = { version = "0.1.0", path = "../api", default_features = false, features = [
  "blocking"
] }
facti-lib = { version = "0.1.0", path = "../lib" }
git2 = { version = "0.17.2", default-features = false }
indoc = "2.0.3"
ron = { version = "0.8.1", optional = true }
rpassword = "7.2.0"
serde = "1.0.183"
serde-lexpr = { version = "0.1.3", optional = true }
serde_json = "1.0.104"
serde_yaml = { version = "0.9.25", optional = true }
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", features = ["serde"] }
