[package]
name = "facti"
version = "0.1.0"
authors = ["Adam Hellberg <sharparam@sharparm.com>"]
edition = "2021"
description = "Factorio mod tool"
homepage = "https://github.com/Sharparam/facti"
repository = "https://github.com/Sharparam/facti"
license = "MPL-2.0"
keywords = ["factorio"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
facti-api = { version = "0.1.0", path = "../api" }
facti-lib = { version = "0.1.0", path = "../lib" }
serde_json = "1.0.104"
url = { version = "2.4.0", features = ["serde"] }
