baseURL = "https://facti.rs/"
defaultContentLanguage = "en"
languageCode = 'en-us'
paginate = 100
timeZone = "Europe/Stockholm"
title = "Facti"
#theme = "simplecss"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Changelogs"
pageRef = "/changelogs"
weight = 20
# [[menu.main]]
# name = "GitHub"
# url = "https://github.com/Sharparam/facti"
# weight = 100

[module]
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/simple-icons'
