[package]
name = "facti-api"
version = "0.1.0"
authors = ["Adam Hellberg <sharparam@sharparam.com>"]
edition = "2021"
description = "Provides tools for interacting with Factorio REST APIs"
homepage = "https://github.com/Sharparam/facti/tree/main/crates/api"
repository = "https://github.com/Sharparam/facti"
license = "MPL-2.0"
keywords = ["factorio"]

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
facti-lib = { version = "0.1.0", path = "../lib" }
reqwest = { version = "0.11.18", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.44"
url = { version = "2.4.0", features = ["serde"] }
