name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --release --workspace
      - name: Generate manpages
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: man
      - name: Copy generated docs to static/doc
        run: cp -r target/doc/* site/static/doc
      - name: Prepare man directory
        run: mkdir site/static/man
      - name: Generate HTML versions of manpages
        run: |
          for f in target/assets/man/*; do
            name=${f##*/}
            out="site/static/man/${name}.html"
            echo "Generating HTML (${out}) for manpage ${f}"
            pandoc --verbose --from man --to html5 --output "${out}" "${f}"
          done
      - name: Prepare staging location
        run: rm -rf _site
      - name: Cache Hugo modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('site/**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build site
        run: hugo --logLevel info --destination _site --minify --source site
      - name: Move generated site to root
        run: mv site/_site _site
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
