on:
  push:
  pull_request:

name: Lint

permissions:
  contents: read
  checks: write

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Run cargo fmt
        run: cargo fmt --all --check --verbose
      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-features -- -D warnings
