name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        type: string

permissions:
  contents: read

jobs:
  defines:
    name: Define variables
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.print-tag.outputs.tag }}
    steps:
      - name: Set tag
        id: print-tag
        run: echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
  cargo-publish:
    runs-on: ubuntu-latest
    needs: defines
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.defines.outputs.tag }}
          fetch-depth: 0
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Publish facti to crates.io
        run: cargo publish --package --token ${CRATESIO_API_TOKEN}
        env:
          CRATESIO_TOKEN: ${{ secrets.CRATESIO_API_TOKEN }}
