on:
  pull_request:
  push:

name: Test

env:
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    env:
      CARGO_INCREMENTAL: 0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ matrix.rust }}-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --verbose
