on:
  pull_request:
  push:

name: Test

permissions:
  contents: read
  checks: write

env:
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    env:
      CARGO_INCREMENTAL: 0
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ matrix.rust }}-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Build
        run: cargo build --release --all-features --verbose
      - name: Test
        run: cargo test --all-features --verbose
